sudo: required

language: c

services:
    - docker

before_install:
    - cd ../
    - git clone https://github.com/fedora-selinux/selinux-policy.git
    - git clone https://github.com/containers/container-selinux.git
    - cp selinux-policy-contrib/* selinux-policy/policy/modules/contrib/
    - cp container-selinux/container.* selinux-policy/policy/modules/contrib/
    - docker pull fedora:rawhide

script:
    - docker run  -v $PWD:/root/build/ fedora:rawhide /bin/sh -c "dnf install -y checkpolicy policycoreutils-devel make m4 git findutils gcc ; cd /root/build/selinux-policy; make policy"

notifications:
    emails:
        - lvrabec@redhat.com
        - zdenek@pytela.net
